### ISSUE TITLE
Dega defaults for the organizations

### ISSUE THREAD

**Issue by deshetti** [factly/dega-server#135]
- No. of spaces. Default: 0. -1 should be made unlimited spaces.
- No. of posts per space. Default: 10. -1 should be made unlimited posts.
- No. of media items per space. Default: 10. -1 should be made unlimited items.

The above defaults should be configurable through env variables.

**Comment by hetjagani** [comment]
No of authors can't be handled in dega-server as authors are added in an organisation at kavach level.
